//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuestionsBase.Views.Home {
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class Index : RazorEngine.Templating.TemplateBase<System.Object> {
        
#line hidden
        
        public Index() {
        }
        
        public override void Execute() {
WriteLiteral("\n");

  
    ViewBag.Title = "Index";

WriteLiteral("\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n        <h2>QuestionBase - A way to test your knowledge</h2>\r\n        <h3>Why " +
"is this useful?</h3>\r\n        \r\n    </div>\r\n    \r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(@">
        <span>
            The Project idea is to be able to create your own base of questions and then to be able to go through them when you are preparing for an interview.
        </span>
        <br /><br />
        <span>
            You will be able to see the question, then think for a while and can see the answer. Very simple, but good place to store all the nasty interview questions.
        </span>
    </div>
</div>");

        }
    }
}
